import { ProductProps } from "./types";

export const products: ProductProps[] = [
  {
    id: 1,
    images: ["/products/blackpink-tote-1.webp"],
    name: "blackpink-tote",
    price: 26.5,
    categories: ["in-your-area"],
    sizes: [],
    discount: 10,
    captions: "Black canvas tote with printed BLACKPINK logo on one side.",
  },
  {
    id: 2,
    images: [
      "/products/blackpink-face-mask-pink-logo-1.webp",
      "/products/blackpink-face-mask-pink-logo-2.webp",
      "/products/blackpink-face-mask-pink-logo-3.webp",
    ],
    name: "blackpink-face-mask-pink-logo",
    price: 9.99,
    categories: ["in-your-area"],
    sizes: [],
    discount: 50,
    captions: "Screenprinted graphic.",
  },
  {
    id: 3,
    images: [
      "/products/the-album-version1-1.webp",
      "/products/the-album-version1-2.webp",
      "/products/the-album-version1-3.webp",
    ],
    name: "the-album-version1",
    price: 30,
    categories: ["the-album", "music"],
    sizes: [],
    discount: 0,
    captions: `"THE ALBUM" Includes: a Package Box (4 different versions), Hardcover Photobook (96 pages), CD, Postcard Set (4 unique cards), Credits Sheet, Photocards (2 of 20, random), Postcards (2 of 20, random), Sticker (1 of 4, random), Mounted Photocard.`,
  },
  {
    id: 4,
    images: [
      "/products/the-album-version2-1.webp",
      "/products/the-album-version2-2.webp",
      "/products/the-album-version2-3.webp",
    ],
    name: "the-album-version2",
    price: 30,
    categories: ["the-album", "music"],
    sizes: [],
    discount: 0,
    captions: `"THE ALBUM" Includes: a Package Box (4 different versions), Hardcover Photobook (96 pages), CD, Postcard Set (4 unique cards), Credits Sheet, Photocards (2 of 20, random), Postcards (2 of 20, random), Sticker (1 of 4, random), Mounted Photocard.`,
  },
  {
    id: 5,
    images: [
      "/products/the-album-t-shirt-ii-1.webp",
      "/products/the-album-t-shirt-ii-2.webp",
    ],
    name: "the-album-t-shirt-ii",
    price: 35,
    categories: ["the-album", "apparel"],
    sizes: ["m", "l", "xl", "2x"],
    discount: 0,
    captions: `Screenprinted graphic`,
  },
  {
    id: 6,
    images: [
      "/products/born-pink-standard-digipack-rose-1.webp",
      "/products/born-pink-standard-digipack-rose-2.webp",
    ],
    name: "born-pink-standard-digipack-rose",
    price: 26,
    categories: ["born-pink", "music"],
    sizes: [],
    discount: 0,
    captions: `Grey washed tee featuring The Album graphic and tracklist.`,
  },
  {
    id: 7,
    images: [
      "/products/born-pink-standard-digipack-jennie-1.webp",
      "/products/born-pink-standard-digipack-jennie-2.webp",
    ],
    name: "born-pink-standard-digipack-jennie",
    price: 26,
    categories: ["born-pink", "music"],
    sizes: [],
    discount: 0,
    captions: `Grey washed tee featuring The Album graphic and tracklist.`,
  },
  {
    id: 8,
    images: [
      "/products/born-pink-standard-digipack-lisa-1.webp",
      "/products/born-pink-standard-digipack-lisa-2.webp",
    ],
    name: "born-pink-standard-digipack-lisa",
    price: 26,
    categories: ["born-pink", "music"],
    sizes: [],
    discount: 0,
    captions: `Grey washed tee featuring The Album graphic and tracklist.`,
  },
  {
    id: 9,
    images: [
      "/products/born-pink-standard-digipack-jisoo-1.webp",
      "/products/born-pink-standard-digipack-jisoo-2.webp",
    ],
    name: "born-pink-standard-digipack-jisoo",
    price: 26,
    categories: ["born-pink", "music"],
    sizes: [],
    discount: 0,
    captions: `Grey washed tee featuring The Album graphic and tracklist.`,
  },
  {
    id: 10,
    images: [
      "/products/born-pink-photo-grid-hoodie-1.webp",
      "/products/born-pink-photo-grid-hoodie-2.webp",
    ],
    name: "born-pink-photo-grid-hoodie",
    price: 80,
    categories: ["born-pink", "apparel"],
    sizes: ["s", "m", "l", "xl", "2xl"],
    discount: 0,
    captions: `Screenprinted graphic`,
  },
  {
    id: 11,
    images: [
      "/products/ice-cream-tie-dye-t-shirt-1.webp",
      "/products/ice-cream-tie-dye-t-shirt-2.webp",
      "/products/ice-cream-tie-dye-t-shirt-3.webp",
    ],
    name: "ice-cream-tie-dye-t-shirt",
    price: 35,
    categories: ["apparel"],
    sizes: ["xl", "2xl"],
    discount: 0,
    captions: `Screenprinted graphic`,
  },
  {
    id: 12,
    images: [
      "/products/blackpink-athletic-pink-puff-print-sweatpants-1.webp",
      "/products/blackpink-athletic-pink-puff-print-sweatpants-2.webp",
      "/products/blackpink-athletic-pink-puff-print-sweatpants-3.webp",
    ],
    name: "blackpink-athletic-pink-puff-print-sweatpants",
    price: 35,
    categories: ["apparel"],
    sizes: ["2xl"],
    discount: 0,
    captions: `Puff Print screenprinted graphic`,
  },
];
